package abc.oracle.apps.fnd.server;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.jbo.RowSetIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrainingServAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public TrainingServAMImpl() {
    }
    
    // Delete the selected rows
    public void deleteDeptRows(){
        XxabcDeptEOVOImpl vo = getXxabcDeptEOVO1();
        XxabcDeptEOVORowImpl row = null;
        // RowSetIterator is like a cursor holding all the rows
        RowSetIterator rowIter = vo.createRowSetIterator("DeptRowIter");
        String deptNoList = "";
        
        while(rowIter.hasNext()){
            row = (XxabcDeptEOVORowImpl)rowIter.next();// get the current row
            String selectFlagStr = row.getselectFlag();// to check selected
            String deptNoStr = row.getDeptno().stringValue();
            
            System.out.println("Dept No="+deptNoStr+" Select Flag="+selectFlagStr);
            
            if(selectFlagStr != null && "Y".equals(selectFlagStr)){
                deptNoList += deptNoStr+",";
                row.remove();// remove the row
            }
            
        }
        
        // like closing the cursor
        rowIter.closeRowSetIterator();
        getOADBTransaction().commit();// commit the delete
        
        throw new OAException("Depts delete are:"+deptNoList, OAException.INFORMATION);
        
    }
    
    // insert Row
    public void insertDeptEOVORow(){
        XxabcDeptEOVOImpl vo = getXxabcDeptEOVO1();
        XxabcDeptEOVORowImpl row = null;
        
        row = (XxabcDeptEOVORowImpl)vo.createRow();
        row.setNewRowState(row.STATUS_INITIALIZED);
        //insert the created row to the VO
        vo.insertRow(row);
        
    }
    
    // Save the Data
    public void saveDeptEOVO(){
        getOADBTransaction().commit();
        throw new OAException("Data saved successfully",
                              OAException.INFORMATION);
    }
    
    public void initDeptEOVO(){
        XxabcDeptEOVOImpl vo = getXxabcDeptEOVO1();
        vo.clearCache();
        vo.setWhereClause(null);
        vo.executeQuery();
        vo.getViewCriteria();
    }

    /**Container's getter for XxabcDeptEOVO1
     */
    public XxabcDeptEOVOImpl getXxabcDeptEOVO1() {
        return (XxabcDeptEOVOImpl)findViewObject("XxabcDeptEOVO1");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("abc.oracle.apps.fnd.server", /* package name */
      "TrainingServAMLocal" /* Configuration Name */);
    }
}
