package abc.oracle.apps.fnd.server;

import abc.oracle.apps.fnd.poplist.server.InventoryOrgPopVOImpl;

import java.io.IOException;
import java.io.OutputStream;

import java.sql.SQLException;

import oracle.apps.fnd.common.MessageToken;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.jbo.RowSetIterator;
import oracle.jbo.XMLInterface;

import oracle.jbo.domain.BlobDomain;

import oracle.xml.parser.v2.XMLNode;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrainingAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public TrainingAMImpl() {
    }
    
    public void initGraphQuery(){
        PositionGraphVOImpl vo = getPositionGraphVO1();
        
        if (vo == null){
            MessageToken[] tokens = {new MessageToken("OBJECT_NAME", "PositionGraphVO1")};
            throw new OAException("AK", "FWK_TBX_OBJECT_NOT_FOUND", tokens);
        }
        
        if (!vo.isPreparedForExecution()) {
            vo.executeQuery();
        }
        
    }
    
    public void initEmpVO(){
        XxabcEmpEOVOImpl vo = getXxabcEmpEOVO1();
        vo.clearCache();
        vo.executeQuery();
    }
    
    public void empSave(){
        getOADBTransaction().commit();
        throw new OAException("Data saved successfully", OAException.INFORMATION);
    }
    
    public void iterateEmpVO(){
        XxabcEmpEOVOImpl vo = getXxabcEmpEOVO1();
        XxabcEmpEOVORowImpl row = null;
        RowSetIterator rowIter = vo.createRowSetIterator("EmpIter");
        
        System.out.println("****Emp Data****");
        
        while(rowIter.hasNext()){
            row = (XxabcEmpEOVORowImpl)rowIter.next();
            System.out.println("Emp Name="+row.getEname()+", Select Flag="+row.getselectFlag());
        }
        
        rowIter.closeRowSetIterator();
    }
    
    public void deleteEmpRows(){
        XxabcEmpEOVOImpl vo = getXxabcEmpEOVO1();
        XxabcEmpEOVORowImpl row = null;
        RowSetIterator rowIter = vo.createRowSetIterator("EmpIter");
        
        System.out.println("****Emp Data****");
        String empNos = "";
        
        
        while(rowIter.hasNext()){
            row = (XxabcEmpEOVORowImpl)rowIter.next();
            System.out.println("Emp Name="+row.getEmpno()+", Select Flag="+row.getselectFlag());
            
            if(row.getselectFlag() != null && "Y".equals(row.getselectFlag())){
                empNos += row.getEmpno()+",";
                row.remove();
            }
            
        }
        
        rowIter.closeRowSetIterator();
        getOADBTransaction().commit();
        throw new OAException ("Emp Nos deleted="+empNos, OAException.INFORMATION);
    }    
    
    public void deleteEmpRowsNew(){
        XxabcEmpEOVOImpl vo = getXxabcEmpEOVO1();
        XxabcEmpEOVORowImpl row = null;
        oracle.jbo.Row[] rows = vo.getFilteredRows("selectFlag", "Y");
        int rowLength = rows.length;
        String empNos = "";
        
        if(rowLength > 0){
            for(int i=0;i<rows.length;i++){
                row = (XxabcEmpEOVORowImpl)rows[i];
                empNos += row.getEmpno()+",";                
                row.remove();
            }
        }
        else{
            throw new OAException("No rows selected for deletion", OAException.INFORMATION);
        }
        
        getOADBTransaction().commit();
        throw new OAException ("Emp Nos deleted="+empNos, OAException.INFORMATION);
    }     
    
    public void insertEmpRow(){
        XxabcEmpEOVOImpl vo = getXxabcEmpEOVO1();
        XxabcEmpEOVORowImpl row = null;
        
        row = (XxabcEmpEOVORowImpl)vo.createRow();
        row.setNewRowState(row.STATUS_INITIALIZED);
        
        oracle.jbo.domain.Number empSeq = getOADBTransaction().getSequenceValue("XXABC_EMPNO");
        row.setEmpno(empSeq);
        
        vo.first();
        vo.insertRow(row);
        
    }
    
    public void initXxabcDeptEOVO(){
        XxabcDeptEOVOImpl vo = getXxabcDeptEOVO1();
        vo.clearCache();
        vo.setWhereClause(null);
        vo.executeQuery();
    }

    public XMLNode getXMLData()
     {
         HrmsEmployeeVOImpl vo = getHrmsEmployeeVO1(); 
         vo.executeQuery();
         XMLNode xmlData = (XMLNode)vo.writeXML(4,XMLInterface.XML_OPT_ALL_ROWS);
         return xmlData;
     }
    
    
    public void initGenerateXMLData(){
        System.out.println("Entered initGenerateXMLData");
        HrmsEmployeeVOImpl vo = getHrmsEmployeeVO1();
        vo.executeQuery();
        
        // write vo data as XMLNode
        XMLNode xmlData = (XMLNode)vo.writeXML(4, XMLInterface.XML_OPT_ALL_ROWS);
        // create a blob variable
        BlobDomain blob = new BlobDomain();
        // Outputstream variable
        OutputStream os = null;

        try {
            // get a blob OutputStream
            os = blob.getBinaryOutputStream();
            // convert the data in OutputStream
            xmlData.print(os);
        } catch (SQLException e) {
            // TODO
        } catch (IOException e) {
            // TODO
        }
        // print the data from OutputStream
        System.out.println(os.toString());
        
        
    }
    
    public void initItemDetailsVO(String orgCode, String itemNumStr){
        ItemDetailsVOImpl vo = getItemDetailsVO1();
        vo.clearCache();
        vo.setWhereClause(null);
        vo.setWhereClauseParam(0, orgCode);
        vo.setWhereClauseParam(1, itemNumStr);
        vo.executeQuery();
    }
    

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("abc.oracle.apps.fnd.server", /* package name */
      "TrainingAMLocal" /* Configuration Name */);
    }

    /**Container's getter for ItemDetailsVO1
     */
    public ItemDetailsVOImpl getItemDetailsVO1() {
        return (ItemDetailsVOImpl)findViewObject("ItemDetailsVO1");
    }

    /**Container's getter for InventoryOrgPopVO1
     */
    public InventoryOrgPopVOImpl getInventoryOrgPopVO1() {
        return (InventoryOrgPopVOImpl)findViewObject("InventoryOrgPopVO1");
    }

    /**Container's getter for HrmsEmployeeVO1
     */
    public HrmsEmployeeVOImpl getHrmsEmployeeVO1() {
        return (HrmsEmployeeVOImpl)findViewObject("HrmsEmployeeVO1");
    }

    /**Container's getter for XxabcDeptEOVO1
     */
    public XxabcDeptEOVOImpl getXxabcDeptEOVO1() {
        return (XxabcDeptEOVOImpl)findViewObject("XxabcDeptEOVO1");
    }

    /**Container's getter for XxabcEmpEOVO1
     */
    public XxabcEmpEOVOImpl getXxabcEmpEOVO1() {
        return (XxabcEmpEOVOImpl)findViewObject("XxabcEmpEOVO1");
    }

    /**Container's getter for PositionGraphVO1
     */
    public PositionGraphVOImpl getPositionGraphVO1() {
        return (PositionGraphVOImpl)findViewObject("PositionGraphVO1");
    }
}
